context:
  version: "0.2.4"
  name: fastapi-zitadel-auth
  python_min: '3.10'

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/f/${{ name }}/fastapi_zitadel_auth-${{ version }}.tar.gz
    sha256: 8a27b36196215bf561588736d7035087315e85ba661a8df6379520056137f339

build:
  script: ${{ PYTHON }} -m pip install .
  noarch: python
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - cryptography >=43.0.3
    - fastapi >=0.115.4
    - httpx >=0.27.2
    - pyjwt >=2.9.0

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - fastapi_zitadel_auth
      pip_check: true

about:
  summary: Zitadel authentication for FastAPI
  license: MIT
  homepage: https://github.com/cleanenergyexchange/fastapi-zitadel-auth
  license_file: LICENCE

extra:
  recipe-maintainers:
    - "0xbe7a"
